name: Makefile CI

on:
  push:
    branches: [ "feature/automate-build" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Compile
      run: make compile
      
    - name: Link
      run: make link
